wolfSSL/wolfHSM

src/wh_nvm_flash.c
test/wh_config.h
test/wh_test_nvm_flash.c

Sets non-zero values in the unused upper bytes of the state variables on the NVM when using nvm_flash subsystem.  This corrects the case when the base NVM uses 0's for Erased AND the EraseVerify/BlankCheck does NOT distinguish, such as the Infineon Tricore.

Fix zeroed state variables on disk.

---

src/wh_flash_ramsim.c
test/Makefile
test/wh_test_flash_ramsim.c

Not the bug we are looking for sadly, but a quick fix: I realized the flash ramsim didn't initialize `ctx->writeLock`, leading to UB that shows up occasionally so want to fix. 
- Fix uninitialized `ctx->writeLock` in flash ramsim
- Add tests for writeLock functionality
- Add `ASAN` makefile option

Flash ramsim uninitialized writeLock fix

---

src/wh_server.c
src/wh_server_crypto.c
wolfhsm/wh_server.h
wolfhsm/wh_server_crypto.h

- Adds support for server-side crypto callbacks
- Some formatting/housekeeping cleanups
Tested full stack on tricore and it works for current crypto tests on `main` (e.g. RNG and Curve25519) !
(` hardware crypto <--> server cryptocb <--> wolfHSM server (HSM) <--| IPC comms |--> wolfHSM client (tricore)`)

Server-side crypto callback support

---

src/wh_client.c
src/wh_server_customcb.c
test/wh_test_clientserver.c
wolfhsm/wh_client.h
wolfhsm/wh_error.h
wolfhsm/wh_message.h

Addresses post-merge comments from #14 
- Renamed WH_ERROR_NO_HANDLER to WH_ERROR_NOHANDLER
- Removed WH_ACTION_MAX
- Add prototype for busy wait CheckRegistered to header.

Quick post-merge fixes

---

test/wh_test_clientserver.c

Test will now fail if server NVM isn't working as expected from the client perspective.
Note: clang-format caused a lot of whitespace changes so recommend you turn off the whitespace diff when looking at the PR in github (Files changed -> settings button -> check hide whitespace)

Added readback/self-checking NVM tests to whTest_ClientServerSequential

---

test/wh_test_clientserver.c
test/wh_test_clientserver.h
wolfhsm/wh_nvm_flash.h

Similar to the NVM and comms test, this PR adds separate client and server test drivers that take a config parameter that can be used outside of a POSIX environment (just the existing "ClientServerSequential" test split up across two functions). This PR then uses those drivers to create a client/server pthread test. 
The diff is kind of confusing to look at, since it is diffing against dead code, so maybe just look at the new functions added.

split client/server tests 

---

src/wh_server.c
src/wh_server_dma.c
src/wh_server_nvm.c
test/Makefile
test/wh_test_clientserver.c
wolfhsm/wh_message_nvm.h
wolfhsm/wh_server.h
wolfhsm/wh_server_dma.h

- Adds support for custom platform-specific DMA callbacks, allowing for injecting operations like cache invalidation, address remapping, etc. before/after accessing client memory
- Adds basic support for memory "allow lists", enabling each server object to maintain a list of allowed regions of system memory that the client is able to read/write from
- Adds the above features to the NVM message handling layer 
- Tests for the above features that run on the POSIX sim and tricore
- data types / address manipulation logic when going between 32/64-bit client addresses and native server addresses
- what should be defined in `wh_server.h` vs `wh_server_dma.h`? Do we want all public server APIs in `wh_server.h` and everything else in the other module? We also have a circular dependency between …

server DMA address handling

---

src/wh_comm.c
test/wh_test_clientserver.c
test/wh_test_crypto.c

Fixes the comm bug now that we allow NULL data pointers.  Fixes test to assert on thread test failure.

Fix comm error and improve test to report failure.

---

.github/workflows/build-and-test.yml
port/posix/posix_flash_file.h
port/posix/posix_transport_tcp.h
src/wh_client.c
src/wh_client_cryptocb.c
src/wh_server.c
src/wh_server_crypto.c
src/wh_server_dma.c
src/wh_server_keystore.c
test/Makefile
test/wh_test.c
test/wh_test_clientserver.c
test/wh_test_crypto.c
wolfhsm/wh_client.h
wolfhsm/wh_comm.h
wolfhsm/wh_common.h
wolfhsm/wh_flash_ramsim.h
wolfhsm/wh_message_nvm.h
wolfhsm/wh_nvm_flash.h
wolfhsm/wh_server.h
wolfhsm/wh_transport_mem.h

1. Support for doing a no crypto build and enabling -Wpadded on all of wolfHSM.
2. Adds additional workflow action to run this build
3. Corrects some wolfCrypt conditional compile misses.  Note WOLFSSL_KEY_GEN is required on server for now.
4. Reorders structures and adds additional padding bytes.

No crypto and padding

---

src/wh_client.c
src/wh_comm.c
src/wh_server.c
src/wh_server_crypto.c
src/wh_server_keystore.c
test/wh_test_clientserver.c
test/wh_test_comm.c
test/wh_test_crypto.c
wolfhsm/wh_client.h
wolfhsm/wh_comm.h
wolfhsm/wh_common.h
wolfhsm/wh_server_crypto.h
wolfhsm/wh_server_keystore.h

splitting the key handle up into 3 parts internally, while presenting a one byte key id to the user, allows the same external or user facing key to be identical for each user value and between SHE and crypto keys. algorithm types were added as flags instead of being a part of the key handle and the user param was added to the client so a user can split operations between 16 clients. may not fully implement multiple client handling but seems good for keys

use key type and key user as part of the internal keyId

---

src/wh_server_crypto.c
test/wh_test_clientserver.c
test/wh_test_crypto.c
test/wh_test_flash_ramsim.c

adds some casting for print statements and `word32` pointers so compiler doesn't complain about `unsigned long int` vs `unsigned int` discrepancy on 32-bit platforms

compiler warning fixes for 32-bit platforms

---

src/wh_comm.c
test/wh_test_clientserver.c
wolfhsm/wh_comm.h

Adds support for client connect callbacks, which should signal to the server via external mechanism that the shared memory comms buffer is ok to process. The server is expected to handle this signal and call `wh_Server_SetConnected()` with the connect value.
How I expose the server context in the tests is kind of janky, but can't really think of another way to do it, since it needs a pointer to the server context which is a local variable to the test function :-/

client connect callbacks

---

wolfhsm/wh_client.h
wolfhsm/wh_server.h

- Add doxygen documentation for public client+server API
- clang-format
Right now it the doxygen is just present in the header. I can also put it in the `.c` file (my typical method) or can duplicate the header into a "documentation" version like wolfSSL does.

first pass at client and server doxygen API

---

src/wh_client.c
src/wh_client_cryptocb.c
wolfhsm/wh_client_cryptocb.h

- Adds a compile-time check for wolfCrypt's `HAVE_ANONYMOUS_INLINE_AGGREGATES` macro to ensure the `wc_CryptoInfo` structure used in our client crypto callback is unionized. This is required as we assume it is in a few different places
- Renames client crypto callback header file to match the source file

static check for structure unionization

---

.github/workflows/build-and-test.yml
src/wh_client.c
test/Makefile
test/wh_test_check_struct_padding.c
test/wh_test_clientserver.c
test/wh_test_clientserver.h
test/wh_test_crypto.c
wolfhsm/wh_client.h
wolfhsm/wh_common.h
wolfhsm/wh_message_comm.h

- Decreased `WOLFHSM_NUM_RAMKEYS` from 16 to 8 for smaller defaults
- Moved counter tests to `wh_test_clientserver.c`
- No longer protecting client counter and keymgr APIs with `WOLFHSM_NO_CRYPTO` (that macro should only mean we aren't building with wolfcrypt suppport)
- Removes use of `XMEMCPY` from functions that are used when `WOLFHSM_NO_CRYPTO` is defined. This is a temporary workaround, but right now since `XMEMCPY` is defined in `user_settings.h`, which is not included when `WOLFHSM_NO_CRYPTO` is defined, then we get compiler errors. If we want `XMEMCPY` and `Xwhatever()` to be a thing in wolfHSM we are going to need to do a little bit of work around settings/configuration to make that possible when decoupled from wolfCrypt.
- Added missing includes and a missing printf

Random lingering tricore cleanups

---

src/wh_client.c
src/wh_server.c
src/wh_server_crypto.c
test/wh_test_crypto.c
wolfhsm/wh_client.h
wolfhsm/wh_error.h
wolfhsm/wh_message.h
wolfhsm/wh_server.h

Fixes bugs in CMAC cancellation and adds a few housekeeping items
Notably:
- Server cancellation response was never correctly propagated to the client (multiple areas of code where this had to be fixed)
- Add helpers for server context field setting
- Add comments for non-obvious sections of code
- Spelling fixes

cancellation bugfixes and cleanups

---

src/wh_server_crypto.c

after the message if it's length is not a multiple of block size

use non-fixed block size so we're not hashing data

---

.github/workflows/build-and-test.yml
test/README.md
test/wh_test.c
test/wh_test_clientserver.c
test/wh_test_comm.c
test/wh_test_crypto.c
test/wolfhsm_cfg.h
wolfhsm/wh_client.h

- Fix/workaround for hanging CI tests by disabling custom server logic (@jpbland1 this needs to be fixed, as it was causing the hang). 
- fixes a few macros that were skipped in the last rename PR
- fixes compiler warning in test printfs
- fixes doxygen error that is breaking wolfSSL documentation CI

quick cleanups

---

src/wh_she_common.c
src/wh_she_crypto.c

Another quick fix required by tricore integration: add wh_settings.h include outside macro protection for SHE source code, so it can conditionally compile in/out remainder of code

Fix settings include file order in SHE module

---

src/wh_server_crypto.c
src/wh_server_keystore.c
test/Makefile
wolfhsm/wh_server.h
wolfhsm/wh_server_keystore.h
wolfhsm/wh_settings.h

seperate cache for larger keys so customers with limited memory can still store a limited number of large keys alongside their smaller keys.

refactor the HSM server and keystore to handle a

---

.github/workflows/build-and-test.yml
test/Makefile
test/wh_test.c
test/wh_test_wolfcrypt_test.c
test/wh_test_wolfcrypt_test.h

Creates a unit test to run wolfCrypt tests on top of wolfHSM, and adds as a CI job. 
This will keep failing CI until we can actually pass wolfCrypt tests, so I've got it **off by default in the unit tests** (use `TESTWOLFCRYPT=1` to enable), and have it set to pass CI even though unit tests fail. 
Once we are able to pass wolfCrypt tests, we can remove the `||true` in the CI job. For now, it is just nice to have as a progress indicator.

Add wolfCrypt tests to unit tests

---

test/wh_test_wolfcrypt_test.c

Forgot to add client cleanup to wolfCrypt test driver

add missing comm/client cleanup functions to wolfCrypt test

---

.gitignore
src/wh_client_cryptocb.c

Fixes missing macro protection
wolfCrypt [guards the definition](https://github.com/wolfSSL/wolfssl/blob/master/wolfssl/wolfcrypt/cryptocb.h#L280-L283) of wcCryptoInfo->cipher by `#if !defined(NO_AES) || !defined(NO_DES3)`, but wolfHSM doesn't, resulting in a compile error when using wolfCrypt with no support for those algos (e.g. default wolfBoot)

fix cryptoCb cipher macro

---

src/wh_client_cryptocb.c
src/wh_server_crypto.c
src/wh_transport_mem.c
src/wh_utils.c
wolfhsm/wh_settings.h
wolfhsm/wh_transport_mem.h
wolfhsm/wh_utils.h

First stage of a sequence of fixes.  This one adds cache flush/mem fencing support to mem transport, stolen from the Bernina private repo, which corrects the surprisingly relaxed memory consistency on Apple silicon when running the sim.

Fix memtransport, move debug prints to utils

---

wolfhsm/wh_settings.h

GCC defines `__GNUC__ `, not `__GCC__`. I have no idea why this isn't throwing warnings on CI (which uses GCC) - but it won't compile locally for me

fix GCC macro

---

.github/workflows/build-and-test.yml
port/posix/README.md
port/posix/posix_flash_file.h
port/posix/posix_transport_shm.c
port/posix/posix_transport_shm.h
port/posix/posix_transport_tcp.c
port/posix/posix_transport_tcp.h
src/wh_client_crypto.c
src/wh_client_cryptocb.c
src/wh_crypto.c
src/wh_server_crypto.c
test/Makefile
test/wh_test_clientserver.c
test/wh_test_comm.c
test/wh_test_crypto.c
wolfhsm/wh_client_crypto.h
wolfhsm/wh_crypto.h
wolfhsm/wh_packet.h
wolfhsm/wh_server_crypto.h
wolfhsm/wh_settings.h

1. Update curve25519 to match ecc code structure.
2. Update posix shm transport to work on MacOS and add optional DMA mappings
3. Clean up tests
4. Correct other typos

Update curve25519 and posixshm transport

---

src/wh_client_cryptocb.c
src/wh_crypto.c

Adds support to the RSA key serialization and deserialization functions for handling public keys (current impl assumes they are private, causing ASN errors to be thrown if used on a public key).
There is no good way to detect if a DER key is private/public, so we now will first attempt to deserialize DER as a private key, and if that fails it falls back to trying it as a public key.
For serialization, it detects the type from `RsaKey->type` field and calls the appropriate serializer.

Add RSA ser/de handling for public keys

---

src/wh_server_keystore.c
tools/whnvmtool/.gitignore
tools/whnvmtool/test/test_whnvmtool.c
tools/whnvmtool/whnvmtool.c

Fixes bug where `hsmFreshenKey()` doesn't actually do what it says it does and load from NVM into cache
Unrelated additions:
- adds license files to `whnvmtool`
- updates `whnvmtool` gitignore

hsmFreshenKey bugfix

---

ChangeLog.md
LICENSING
port/posix/posix_transport_shm.c
port/posix/posix_transport_shm.h
test/wh_test_check_struct_padding.c
test/wh_test_she.h

1. Added missing GPLv3 license text in some source.
2. Added LICENSING note.
3. Added ChangeLog

Update to support relicensing to commercial license

---

src/wh_server_crypto.c

Fix bug where error codes returned from wolfCrypt were stored in an unsigned value, preventing the error from being detected and leading to read of garbage comm buffer data on the client side

Fix ECC verify bug

---

src/wh_client_cryptocb.c

wolfBoot CI flagged an unsued argument in a static function. I originally added before splitting DMA ops into their own cryptoCb so these should never have been there in the first place.

quick fix: remove unused arg

---

.github/workflows/build-and-test.yml
src/wh_client_crypto.c
src/wh_crypto.c
src/wh_server_crypto.c
src/wh_server_keystore.c
test/wh_test.c
wolfhsm/wh_crypto.h

Fixes curve25519 implementation, changing it to use new [wolfCrypt DER API ](https://github.com/wolfSSL/wolfssl/pull/8129) for ser/de instead of raw keys

Curve25519 fixes

---

.github/workflows/build-and-test.yml
ChangeLog.md
test/wh_test_she.c

Fixes a memory leak in the SHE tests caused by not freeing the RNG used to generate arbitrary test data.
We weren't running SHE tests under ASAN for some reason. When I turned it on, it flagged the leak.

Fix memory leak in SHE tests

---

src/wh_client_crypto.c
src/wh_client_cryptocb.c
src/wh_server_crypto.c
src/wh_server_keystore.c
src/wh_utils.c
test/wh_test_check_struct_padding.c
test/wh_test_crypto.c
wolfhsm/wh_client_crypto.h
wolfhsm/wh_packet.h

Adds DMA support for CMAC. Can be used via ANY of wolfCrypt's CMAC APIs that accept a devId.
Passes wolfHSM and wolfCrypt tests on both POSIX sim and TC3xx.
A bit of a noisy diff, as I ran clang-format on some bigger blocks of code.
Future work:
- Overhaul existing non-DMA CMAC, specifically pushing state storage back to the client
- Remove all 32/64 bit public DMA APIs and replace with 64-bit messages only

DMA support for CMAC

---

port/posix/posix_flash_file.c
src/wh_flash_unit.c
src/wh_server_crypto.c
test/user_settings.h
test/wh_test_crypto.c
test/wh_test_nvm_flash.c
test/wh_test_nvm_flash.h
wolfhsm/wh_error.h
wolfhsm/wh_flash.h

1. Correct potential flash_unit error where program was being called with a 0 count.
2. Add standalone flash and flash_unit tests.
3. Shift wh_error codes to not conflict with wolfcrypt/error-ssl.h codes
4. Use wolfcrypt CURVE25519 export buffer size if available.
5. Update wh_flash.h interface documentation to better explain the expected behavior.

Fix flashunit program

---

src/wh_client_crypto.c
src/wh_server_keystore.c

When building wolfHSM-examples, a couple of config errors were found:
1. _create_crypto_request_with_subtype was never called when pqc in not enabled.  Fixed by routing _crete_crypto_request through this function
2. sha256->flags only exists when WOLFSSL_HASH_FLAGS is set, which is not required.  Fix conditionally handles this.
3. only provide key export data on non-error.

Fix a few compile errors  due to config

---

src/wh_client_cryptocb.c
src/wh_server_crypto.c

Fixes warnings on 32-bit targets

quickfix: compiler warnings for 32-bit targets

---

src/wh_server_crypto.c

[Upstream wolfSSL ](https://github.com/wolfSSL/wolfssl/pull/8736)broke wolfHSM after it turned on curve25519 blinding by default, which requires setting RNG on key context for shared secret generation. Found out the hard way after updating wolfSSL to latest master. This PR fixes.

set RNG on curve25519 keys to support blinding

---

test/wh_test_crypto.c

Fixes use of uninitialized variable as buffer size in/out argument, which caused sporadic test failures on hardware platforms

Keycache test fixes

---

src/wh_server_crypto.c

I'm puzzled how static analysis or ASAN can miss this. 
At least for ASAN, I think the reason is that the Aes struct is big enough to don't overflow the struct.
making the struct smaller by removing HAVE_AES_GCM triggers an error immediately at compile time with clang
```
clang  -std=c90 -Werror -Wall -Wextra -ffunction-sections -fdata-sections -ggdb -g3 -fsanitize=address -D_POSIX_C_SOURCE=200809L -DWOLFSSL_USER_SETTINGS -DWOLFHSM_CFG -DWOLFHSM_CFG_TEST_POSIX -DWOLFHSM_CFG_DMA -DWOLFHSM_CFG_ENABLE_CLIENT -DWOLFHSM_CFG_ENABLE_SERVER -DWOLFHSM_CFG_IS_TEST_SERVER -I. -I./config -I../../wolfssl -I../ -I..//port/posix -c -o Build/wh_server_crypto.o ..//src/wh_server_crypto.c
..//src/wh_server_crypto.c:1374:13: error: 'memcpy' will always overflow; destination buffer has size 160, but size …
```

crypto: aesctr: fix: use correct buffer size in memcpy for tmp

---

src/wh_client_cryptocb.c

Adds missing macro protection (`WOLFSSL_SHA512_HASHTYPE`) to usage of `wh_Client_Sha512Dma()` who's definition is guarded by said macro

quickfix: add missing macro protection

---

.github/workflows/clang-format-check.yml

Adds a GH action that enforces code formatting on a PR (only on the diff against the PR target branch, not on all files).
The action runs `git-clang-format` against the target branch (usually `main`) to see if there are any formatting changes that would be made (indicating the PR author didn't run the command locally). If there are changes, the action fails, prompting the PR author to run `git-clang-format` locally and commit the changes.

Reject unformatted PRs

---

port/posix/posix_transport_shm.c

PR (https://github.com/wolfSSL/wolfHSM/pull/158) I missed updating the setting of heap hint in the provided DMA static memory callback function.

fix for callback heap hint used

---

benchmark/bench_modules/wh_bench_mod_rsa.c
examples/demo/client/wh_demo_client_crypto.c
examples/demo/client/wh_demo_client_secboot.c
examples/posix/wh_posix_server/wh_posix_server.c
examples/posix/wh_posix_server/wh_posix_server_cfg.c
src/wh_nvm_flash.c
src/wh_server_crypto.c
test/wh_test_clientserver.c
test/wh_test_crypto.c

Fixes issues on scan-build LLVM-19
```
scan-build --status-bugs make -C test/ 
scan-build --status-bugs make -C benchmark/ 
scan-build --status-bugs make -C examples/ 
scan-build --status-bugs make -C tools/whnvmtool/
```
There is one issue, which is `warning: Value stored to 'ret' is never read` in `wolfcrypt\src\random.c` against `tools/whnvmtool/`, remaining. That will be separately fixed.
Github action addition for changes in the future will be submitted as separate PR.

Fixes scan-build issues 
